# Generated by Django 5.2.4 on 2025-07-10 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('detail', models.TextField()),
                ('status', models.CharField(choices=[('open', '募集中'), ('closed', '募集終了')], max_length=10)),
            ],
        ),
    ]
