# Generated by Django 5.2.4 on 2025-07-14 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': '案件', 'verbose_name_plural': '案件一覧'},
        ),
    ]
