# Generated by Django 5.2.4 on 2025-07-18 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='customer_name',
        ),
        migrations.AddField(
            model_name='project',
            name='customer_person',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='顧客担当者名'),
        ),
        migrations.AddField(
            model_name='project',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projects.customer'),
            preserve_default=False,
        ),
    ]
