# Generated by Django 5.2.4 on 2025-07-18 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_customer_remove_project_customer_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': '顧客', 'verbose_name_plural': '顧客一覧'},
        ),
    ]
