# Generated by Django 5.2.4 on 2025-07-18 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_customer_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': '案件', 'verbose_name_plural': '案件一覧'},
        ),
    ]
