# Generated by Django 5.2.4 on 2025-07-14 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='氏名')),
                ('bio', models.TextField(verbose_name='紹介文')),
                ('experience_years', models.PositiveIntegerField(default=0, verbose_name='経験年数')),
            ],
        ),
    ]
