# Generated by Django 5.2.4 on 2025-07-14 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='experience_years',
        ),
        migrations.AddField(
            model_name='employee',
            name='introduction',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='join_date',
            field=models.DateField(auto_now_add=True, default='2025-07-14'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
