# Generated by Django 5.2.4 on 2025-07-14 09:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_remove_employee_bio_remove_employee_experience_years_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='join_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
