# Generated by Django 5.2.4 on 2025-07-14 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_employee_join_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='join_date',
            new_name='recorded_at',
        ),
        migrations.AddField(
            model_name='employee',
            name='base_experience',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
