# Generated by Django 5.2.4 on 2025-07-14 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_rename_join_date_employee_recorded_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='base_experience',
            field=models.PositiveIntegerField(default=0, verbose_name='経験年数初期値'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='introduction',
            field=models.TextField(verbose_name='紹介文'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=100, verbose_name='氏名'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='recorded_at',
            field=models.DateField(auto_now_add=True, verbose_name='登録日'),
        ),
    ]
