# Generated by Django 5.2.4 on 2025-07-14 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_alter_employee_base_experience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='base_experience',
            field=models.PositiveIntegerField(default=18),
        ),
        migrations.AlterField(
            model_name='employee',
            name='introduction',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='recorded_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
