# Generated by Django 5.2.4 on 2025-07-14 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_alter_employee_base_experience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='base_experience',
            field=models.PositiveIntegerField(default=18, verbose_name='年数初期値'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='introduction',
            field=models.TextField(verbose_name='紹介文'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=100, verbose_name='氏名'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='recorded_at',
            field=models.DateField(auto_now_add=True, verbose_name='記録日'),
        ),
    ]
