# Generated by Django 5.2.4 on 2025-07-14 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_alter_employee_base_experience_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': '社員', 'verbose_name_plural': '社員一覧'},
        ),
    ]
