# Generated by Django 5.2.4 on 2025-07-14 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_alter_employee_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': '社員', 'verbose_name_plural': '社員'},
        ),
    ]
