# Generated by Django 5.2.4 on 2025-07-15 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_alter_employee_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='base_experience',
        ),
        migrations.AddField(
            model_name='employee',
            name='base_age',
            field=models.PositiveIntegerField(default=30, verbose_name='年齢初期値'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='base_industry_year',
            field=models.PositiveIntegerField(default=2024, verbose_name='入業年初期値'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='recorded_at',
            field=models.DateField(auto_now_add=True, verbose_name='作成日'),
        ),
    ]
