# Generated by Django 5.2.4 on 2025-07-16 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_remove_employee_base_experience_employee_base_age_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='base_industry_year',
        ),
        migrations.AddField(
            model_name='employee',
            name='base_experience',
            field=models.PositiveIntegerField(default=0, verbose_name='経験年数初期値'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='base_age',
            field=models.PositiveIntegerField(default=0, verbose_name='年齢初期値'),
        ),
    ]
