# Generated by Django 5.2.4 on 2025-07-24 04:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmail_reader', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='gmailtoken',
            name='refresh_token',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='ImportedMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=128, unique=True)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('sender', models.EmailField(max_length=254)),
                ('received_at', models.DateTimeField()),
                ('snippet', models.TextField(blank=True, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
