# Generated by Django 5.2.4 on 2025-07-24 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmail_reader', '0002_alter_gmailtoken_refresh_token_importedmail'),
    ]

    operations = [
        migrations.AddField(
            model_name='importedmail',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
    ]
